<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Application</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\iot_hub.Contracts\iot_hub.Contracts.csproj" />
      <ProjectReference Include="..\iot_hub.Domain\iot_hub.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" Version="2.14.2-RC1" />
      <PackageReference Include="Mapster" Version="10.0.8-pre07" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="11.0.0-preview.4.26230.115" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.4.26230.115" />
      <PackageReference Include="Refit" Version="11.0.1" />
    </ItemGroup>

</Project>
